# Generated by Django 5.2.1 on 2025-05-09 17:03

import django.db.models.deletion
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INFLOW', 'Inflow')], max_length=7)),
                ('category', models.ForeignKey(default=transactions.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='transactions.category')),
            ],
        ),
    ]
